/*
Garrett Searls
CSCI 130
Homework 6
Problem 3 - Power Generation
*/
#include <iostream>
#include <iomanip>

using namespace std;

double powerGen(double H, double Q);

int main() {

  
  const double p = 977; // is the water density (kg/m3)
  const double g = 9.8; // is the acceleration caused by gravity (9.81 m/s2).
  double P;             // The power generated by this water flow
  double Q;             // is the volume flow rate (m3/s).
  double H;             // is the distance (in m) water falls on its way to the generator

  cout << "Input the Head distance: ";
  cin >> H;

  cout << "Input the Water Flow Rate: ";
  cin >> Q;

  P = powerGen(H, Q);

  cout << fixed << setprecision(0) << "The power Generated by the Water Flow is: " << P << " watts";

  return 0;

}

double powerGen(double H, double Q)
{
  const double p = 977;
  const double g = 9.8; 

  double P = p * Q * H * g;

  return P;
}


/*
The first test case where the head distance was 14m and the water flow rate was 20m^3/s, the power generated was 2680888 watts
The seconed test case where the head distance was 30m and the waster flow was 20m^3/s, the power generated was 5744760 watts.
Even though the water flow rate was the same in both test cases the second test case shows that as the head distance increases so does the power generated.
*/
